[package]
name = "socks5proxy"
version = "0.1.0"
authors = ["3vilive <ba0ch3ng@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }